In [1]:
import numpy as np

In [6]:
a=np.loadtxt('tipsf.csv',delimiter=',',skiprows=1)

In [7]:
a

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [8]:
# 1Q what is total bill value

In [9]:
# program
np.sum(a[:,1])

4827.77

In [10]:
# 2Q:what is total tip value

In [11]:
#program
np.sum(a[:,2])

731.5799999999999

In [12]:
# 3Q:how many sat ,sun, thu,fri are there?

In [14]:
#program
np.unique(a[:,5],return_counts=True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

In [15]:
# 4Q:how many smokers are there?

In [16]:
# program
np.sum(a[:,4])

93.0

In [17]:
# 5Q:what is the avg tip given by female and male?

In [18]:
# program
np.unique(a[:,3],return_counts=True)

(array([0., 1.]), array([ 87, 157], dtype=int64))

In [19]:
# there are 87 female and 157 male

In [24]:
a1=a[a[:,3]==0].copy()

In [25]:
a1

array([[  0.  ,  16.99,   1.01,   0.  ,   0.  ,   1.  ,   0.  ,   2.  ],
       [  4.  ,  24.59,   3.61,   0.  ,   0.  ,   1.  ,   0.  ,   4.  ],
       [ 11.  ,  35.26,   5.  ,   0.  ,   0.  ,   1.  ,   0.  ,   4.  ],
       [ 14.  ,  14.83,   3.02,   0.  ,   0.  ,   1.  ,   0.  ,   2.  ],
       [ 16.  ,  10.33,   1.67,   0.  ,   0.  ,   1.  ,   0.  ,   3.  ],
       [ 18.  ,  16.97,   3.5 ,   0.  ,   0.  ,   1.  ,   0.  ,   3.  ],
       [ 21.  ,  20.29,   2.75,   0.  ,   0.  ,   0.  ,   0.  ,   2.  ],
       [ 22.  ,  15.77,   2.23,   0.  ,   0.  ,   0.  ,   0.  ,   2.  ],
       [ 29.  ,  19.65,   3.  ,   0.  ,   0.  ,   0.  ,   0.  ,   2.  ],
       [ 32.  ,  15.06,   3.  ,   0.  ,   0.  ,   0.  ,   0.  ,   2.  ],
       [ 33.  ,  20.69,   2.45,   0.  ,   0.  ,   0.  ,   0.  ,   4.  ],
       [ 37.  ,  16.93,   3.07,   0.  ,   0.  ,   0.  ,   0.  ,   3.  ],
       [ 51.  ,  10.29,   2.6 ,   0.  ,   0.  ,   1.  ,   0.  ,   2.  ],
       [ 52.  ,  34.81,   5.2 ,   0.  ,   0.  ,   1

In [27]:
np.sum(a[:,2])/87

8.408965517241379

In [28]:
# avg tip by female is 8.40896

In [29]:
a2=a[a[:,3]!=0].copy()

In [30]:
a2


array([[  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       [  3.  ,  23.68,   3.31, ...,   1.  ,   0.  ,   2.  ],
       ...,
       [239.  ,  29.03,   5.92, ...,   0.  ,   0.  ,   3.  ],
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ]])

In [31]:
np.sum(a[:,2])/157

4.659745222929936

In [32]:
# avg tip given by male is 4.6597

In [33]:
# 6Q: how much amount have been spend by male and female?

In [34]:
# program
f=np.sum(a1[:,1])
m=np.sum(a2[:,1])

In [35]:
"Total amount paid by female and male is {},{}".format(f,m)

'Total amount paid by female and male is 1570.9499999999996,3256.8199999999997'

In [36]:
# 7Q:what is min and max tip?

In [37]:
# program
mim=np.min(a[:,2])
max = np.max(a[:,2])

In [38]:
'max and min tip is {},{}'.format(max,mim)

'max and min tip is 10.0,1.0'

In [39]:
#8Q:how many males and females are going to lunch and dinner?

In [41]:
# program
np.unique(a1[:,6],return_counts=True)

(array([0., 1.]), array([52, 35], dtype=int64))

In [42]:
#52 females are going for dinner and 35 for lunch

In [43]:
np.unique(a2[:,6],return_counts=True)

(array([0., 1.]), array([124,  33], dtype=int64))

In [44]:
#124 men are going for dinner and 33 are for lunch

In [45]:
#9Q:Find out avg size?

In [53]:
# program
x=np.sum(a[:,7])
y=a[:,7].shape
y

(244,)

In [54]:
avg_size = x/244

In [55]:
avg_size

2.569672131147541

In [56]:
#10Q:How many female and male smokers are there?

In [57]:
# program
a1[a1[:,4]==1].shape

(33, 8)

In [58]:
a2[a2[:,4]==1].shape

(60, 8)

In [ ]:
# 33 female smokers and 60 male smokers are there