In [1]:
# 1Q:Write a program to create a 5 dimensional array with all zeros and ones

In [54]:
#program
import numpy as np
np.ones((1,1,1,5,5),dtype=int)

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

In [55]:
#program
np.zeros((1,1,1,5,5),dtype=int)

array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]])

In [4]:
# 2Q:Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which
# create a new array of shape (3,10)

In [8]:
x=np.array([
    np.zeros((10,)),
    np.ones((10,)),
    np.full((10,),5)
],dtype=int)
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [9]:
# 3Q:Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [10]:
# program
arr = np.arange(10,22).reshape(3,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [11]:
# 4Q: Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,

In [12]:
# program
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [13]:
# 5Q:Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns

In [52]:
# program
# given array
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
# program
# manipulated array
arr[::,::-1]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [56]:
# 6Q: Write a program to reverse an array (the first element becomes the last).
#Given array:
#[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [57]:
# program
arr = np.arange(12,28)
arr[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [58]:
# 7Q:Write a program to access all the elements greater than 30 and less than 80 and
# multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [64]:
# program
a = np.arange(1,101).reshape(10,10)
a[((a>30)&(a<80)) & (a%5==0)]


array([35, 40, 45, 50, 55, 60, 65, 70, 75])

In [65]:
# 8Q:Write a program to create a 2D array with 1 on the border and 0 inside.

In [73]:
# program
a = np.zeros((5,5),dtype=int)
a[0]=1
a[4]=1
a[:,0]=1
a[:,4]=1
a


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [80]:
# 9Q:Write a program to create a checkerboard pattern

In [5]:
# program
import numpy as np
a = np.eye(2,dtype=int)
a1 = a[:,::-1]
np.tile(a1,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [74]:
# 10Q:10) Write a program to find common values between two arrays.
#Expected Output:
#array1: [10 20 40 60]
#array2: [10, 30, 40,50]

In [76]:
# program
a1 = np.array([10,20,40,60])
a2 = np.array([10,30,40,50])
set(a1) & set(a2)

{10, 40}

In [77]:
# 11Q:Write a program to create an array 2d array and then reshape into 1d array

In [78]:
# program
a=np.arange(1,17).reshape(4,4)
b=a.flatten()
b
b.ndim

1

In [79]:
# 12Q:Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [9]:
# program
y=[1,2,3,4]
def func_array(x):
    if x==1:
        return  [ i for i in y]
    if x==2:
        rows = int(input("enter rows: "))
        cols = int(input("enter cols: "))
        return  [[0]*cols]*rows


In [10]:
func_array(1)

[1, 2, 3, 4]

In [11]:
func_array(2)

enter rows: 2
enter cols: 3


[[0, 0, 0], [0, 0, 0]]